### ISSUE TITLE
在linux系统中web页面异常

### ISSUE THREAD

**Issue by liuz4i** [RicterZ/BGmi#105]
我在linux系统上web显示异常，在运行bgmi_http命令后web页面显示如下
![default](https://user-images.githubusercontent.com/27472870/33769849-a7ca2b9a-dc66-11e7-87b9-ab7e0d15c447.png)
我尝试了ubunntu17.10 centos7在python3环境下都是同样的情况，而我在win10上使用同样的操作却能够正常运行显示web界面，请问一下这是什么问题？

**Comment by trim21** [comment]
你的nginx没有设置好
```
server {
    listen 80;
    server_name bgmi;

    root /path/to/bgmi;
    autoindex on;
    charset utf-8;

    location /bangumi {
        # ~/.bgmi/bangumi
        alias /path/to/bangumi;
    }

    location /api {
        proxy_pass http://127.0.0.1:8888;
    }

    location /resource {
        proxy_pass http://127.0.0.1:8888;
    }

    location / {
        # ~/.bgmi/front_static/;
        alias /path/to/front_static/;
    }

}
```
先`bgmi install`

**Comment by trim21** [comment]
windows上一般不会有人用nginx,所以是直接用tornado自己代理的前端静态文件...

**Comment by liuz4i** [comment]
问题已经解决了，之后又遇到了403 Forbidden错误，一路坎坷，最后修改了root文件夹权限，总算成功了

**Comment by zzzop** [comment]
请问nginx配置文件只改这一行就可以吗，我改了以后404错误，可以指点一下吗
`    server_name bgmi;`

**Comment by trim21** [comment]
不行 下面几个/path/to/xxx也要改成对应的路径

**Comment by trim21** [comment]
location /bangumi {
        # ~/.bgmi/bangumi
        alias /path/to/bangumi;
    }
alias后面是你的save_path

location / {
        # ~/.bgmi/front_static/;
        alias /path/to/front_static/;
    }
alias后面时bgmi_path/front_static
