### ISSUE TITLE
[bugs]集数不对在此回复issue

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/BGmi#11]

**Comment by RicterZ** [comment]
Show by ROCK!! 集数不对

**Comment by RicterZ** [comment]
@ershiwo 可以通过 pip install bgmi --upgrade 或者 github 上直接升级了

**Comment by ershiwo** [comment]
恩，问题已经解决了。

**Comment by xtdyx001** [comment]
清恋第五集极影的命名方式是这样的
[JYFanSub][SeiRen][2-1][GB_CN][HEVC][720p].mp4
然后bgmi识别成了第一集然后放在了第一集的文件夹内

**Comment by RicterZ** [comment]
@xtdyx001 极影的对吧，按理说集数判断是根据这里来的，应该没问题。。
![image](https://cloud.githubusercontent.com/assets/5282759/22851832/e0cd8454-f068-11e6-8565-f5d4468e6efb.png)

**Comment by xtdyx001** [comment]
我没有选定特定的字幕组，只加了--exclude BIG5

**Comment by RicterZ** [comment]
@xtdyx001 你的那个下载地址是什么？打开 ~/.bgmi/bangumi.db，然后 download 表找一下

**Comment by xtdyx001** [comment]
magnet:?xt=urn:btih:X72NSK7LMM3DJ4R62SLJQSWZYIIHI2XV

**Comment by RicterZ** [comment]
https://dmhy.ricterz.me/topics/view/453394_1_GB_CN_HEVC_720p_MP4.html 
就是这一集，他们这里标写的是第一集，实际下载下来是第二集么？
如果是的话那就是他们把种子地址写错了，可以换个字幕组下载

**Comment by xtdyx001** [comment]
这个是 宫前透篇 第1集，实际上总的第一集应该是 常木耀篇 第1集，清恋这次是每四集一个篇章，其他字幕组都好好的标第5集，就极影要把xx篇写到标题里面Orz

**Comment by RicterZ** [comment]
orz，直接把极影 filter 掉吧..
