### ISSUE TITLE
可否将 DPlayer 部分的文档更细化一些？

### ISSUE THREAD

**Issue by AlanDecode** [RicterZ/BGmi#112]
第一步：`setup nginx to access bangumi files` 是否指在 nginx 的 conf 文件中添加下面的字段？
```
location /bangumi {
        # ~/.bgmi/bangumi
        alias path/to/bgmi/bangumi;
    }
```
之后的步骤就看不太明白了。其余部分应该已经配置好了，页面在：[https://bangumi.imalan.cn/#/](https://bangumi.imalan.cn/#/)，部署在 VPS 上。~~请问需要怎样设置才能在线播放？~~
播放已经OK了，但仍然不会配置弹幕😂

另外，为何剧集即使并没有下载，status也是1或者2？不应该是0吗？

**Comment by RicterZ** [comment]
看你那里好像没什么问题？DPlayer的话，需要参考一下Dplayer的文档，搭建好mongodb和danmaku api。
http://dplayer.js.org/#/zh-Hans/
然后配置：bgmi config DANMAKU_API_URL http://xxxx 即可

**Comment by AlanDecode** [comment]
好的，谢谢~
