### ISSUE TITLE
Python 3.5 and beautifulSoup 4

### ISSUE THREAD

**Issue by LukeXuan** [RicterZ/BGmi#3]
The beautifulSoup 4.4.0 and before versions does not support py 3.5, and this project requires beautifulSoup 4.3.2.

**Comment by RicterZ** [comment]
requests 4.4.0 is broken down with error "SyntaxError: invalid syntax" on python3.2.5
![image](https://cloud.githubusercontent.com/assets/5282759/18240978/56b8f974-7381-11e6-99e7-f64da3834e60.png) 
...

**Comment by LukeXuan** [comment]
well I mean 3.**5**, but not 3.**2.5**...:)

**Comment by LukeXuan** [comment]
current requirement.txt manually tested working on MacOS 10.11, python 3.5. I think you can just push to pypi and I can enjoy it :)

**Comment by RicterZ** [comment]
Yeah I know it. But tests were failed as requests broke down on
python3.2.5, when I modified the requests' version in the requirement.txt.
Luke Lazurite notifications@github.com于2016年9月5日 周一下午5:19写道：

**Comment by RicterZ** [comment]
OK, just a moment.
Ricter Zheng ricterzheng@gmail.com于2016年9月5日 周一下午5:33写道：

**Comment by LukeXuan** [comment]
Well, it seems strange. no python 3.2 environment :(

**Comment by LukeXuan** [comment]
It seems that python 3.2 deleted `u` string literal and 3.3 re-introduce it. That's the problem.

**Comment by RicterZ** [comment]
_(:3」∠)_oh
Luke Lazurite notifications@github.com于2016年9月5日 周一下午5:38写道：

**Comment by RicterZ** [comment]
BGmi has been pushed to pypi :D
