### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by alicenychto** [RicterZ/BGmi#4]
```
alice at nychto in ~ [23:48:18]
$ bgmi cal all
Traceback (most recent call last):
  File "/usr/local/bin/bgmi", line 9, in <module>
    load_entry_point('bgmi==0.4.6', 'console_scripts', 'bgmi')()
  File "/usr/local/lib/python3.5/site-packages/bgmi-0.4.6-py3.5.egg/bgmi/main.py", line 408, in setup
    init_db(DB_PATH)
  File "/usr/local/lib/python3.5/site-packages/bgmi-0.4.6-py3.5.egg/bgmi/main.py", line 395, in init_db
    conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file

```

用pip和pip3安装的结果都是无法运行……

**Comment by RicterZ** [comment]
看起来好像是初始化database失败了…默认是在~/.bgmi 目录，你看一下是不是没有读写权限？
Alice Nychto notifications@github.com于2016年9月11日 周日上午5:52写道：

**Comment by yukiinagato** [comment]
我也遇到了这个问题，一开始是提示 `sqlite3.OperationalError: attempt to write a readonly database` ，尝试进入 ~/.bgmi 更改权限，然后就变 `sqlite3.OperationalError: unable to open database file`
用root权限就解决了……
不知道是哪里姿势不对

**Comment by RicterZ** [comment]
感觉很不科学...什么情况下的呢..
是不是sudo pip install bgmi的。。

**Comment by yukiinagato** [comment]
@RicterZ 嗯……我的是用root权限装的……

**Comment by RicterZ** [comment]
@auzeonfung 我大概知道问题了..
sudo pip install bgmi 的话，HOME 还是你当前普通用户的路径，但是创建路径的时候就是 root 权限创建在你当前用户的 HOME 下的，所以你当前用户没权限写...

**Comment by RicterZ** [comment]
这个 bug 待会儿修（x

**Comment by alicenychto** [comment]
还真是…chmod 777 之后就可以用了（后知后觉

**Comment by RicterZ** [comment]
6b97e4402c61610381d76e968f7d6d53c627b842
fix 了这个问题
