### ISSUE TITLE
BGmi HTTP 页面元素显示有问题

### ISSUE THREAD

**Issue by loggerhead** [RicterZ/BGmi#40]
如图，那个红色圆圈的位置不对：

![a.png](https://ooo.0o0.ooo/2017/02/10/589d2b4e6e78b.png)

* BGmi 版本是 `1.0.23`
* Chrome 版本是 `55.0.2883.95 (64-bit)`
* 系统是 macOS `10.10.5`

**Comment by RicterZ** [comment]
红色圈圈确实是在那个位置的。

**Comment by loggerhead** [comment]
好吧，我还以为你是打算放在字的右边。。
