### ISSUE TITLE
`bgmi download` 的输出

### ISSUE THREAD

**Issue by loggerhead** [RicterZ/BGmi#41]
不管当前有没有下载项，目前 `bgmi download` (BGmi ver. 1.0.23) 的输出都是：

```
Download status value: Not Downloaded: 0 / Downloading: 1 / Downloaded: 2

```

也许将 `bgmi download`  的输出改成 `bgmi download --list` 或 `bgmi download --help` 的输出会更有意义？

**Comment by RicterZ** [comment]
fixed 59b863fd0aedc3220fb50ca3c26408509dbc569e
