### ISSUE TITLE
filter subtitle的问题

### ISSUE THREAD

**Issue by AsakuraFuuko** [RicterZ/BGmi#44]
中间有"."的字幕组，只写前半好像加不进去
> bgmi filter "Urara迷路帖" --subtitle "輕之國度"
> [*] Usable subtitle group: 極影, 西農YUI, 輕之國度.動漫國, DHR
> [+] Added subtitle group:
> [+] Include keywords: None
> [+] Exclude keywords:
> [+] Regular expression: None

全写fetch不到东西
> bgmi filter "Urara迷路帖" --subtitle "輕之國度.動漫國"
> [*] Usable subtitle group: 極影, 西農YUI, 輕之國度.動漫國, DHR
> [+] Added subtitle group: 輕之國度.動漫國
> [+] Include keywords: None
> [+] Exclude keywords:
> [+] Regular expression: None
> 
> bgmi followed --mark "Urara迷路帖" --episode 0
> [+] Followed Bangumi<Urara迷路帖> has been mark as episode: 0
> 
> bgmi fetch "Urara迷路帖"
> [*] Fetch bangumi Urara迷路帖 ...
> [-] Nothing.

**Comment by RicterZ** [comment]
pip 升级之后请用 bgmi upgrade 更新数据库

**Comment by AsakuraFuuko** [comment]
可以了
