### ISSUE TITLE
bgmi cal all 出错, 好像是因为dmhy加了cf？

### ISSUE THREAD

**Issue by AsakuraFuuko** [RicterZ/BGmi#48]
> bgmi cal all
[-] warning: no bangumi schedule, fetching ...
[x] It seems that no bangumi found, if https://dmhy.ricterz.me can
    be opened normally, please report bug to ricterzheng@gmail.com
    or submit issue at: https://github.com/RicterZ/BGmi/issues

**Comment by RicterZ** [comment]
啊…看来是的………

要不然你换到bangumi.moe分支吧…

clone 下来 checkout 过去后安装
AsakuraFuuko <notifications@github.com>于2017年4月5日 周三下午1:49写道：

**Comment by RicterZ** [comment]
目前已经完全支持 bangumi.moe，请用最新版 :D
