### ISSUE TITLE
aria2downloadRPC的代码错误

### ISSUE THREAD

**Issue by trim21** [RicterZ/BGmi#53]
python3.6

```python

class Aria2DownloadRPC(DownloadService):
    @staticmethod
    def download_status(status=None):
         ...
                if Aria2DownloadRPC.old_version:
                    data = server.aria2[method](ARIA2_RPC_TOKEN, *params)
                else:
                    data = server.aria2[method](*params)
         ...
```
不确定旧版本是否需要token,但是新版本是肯定需要的,

应该为
```python
                else:
                    data = server.aria2[method](ARIA2_RPC_TOKEN, *params)
```
原来的代码会报一个unauthorized的错误,反而被错误处理所捕捉.导致在配置正确的情况下仍然报无法链接到rpc服务器的错误,而实际上可以连接

ps:个人感觉aria2用户应该不太会有留在旧版的..可以放弃考虑兼容旧版....

**Comment by RicterZ** [comment]
我蠢了…反过来就好了😂😂
求修复测试通过后提交 PR，我现在在外面没法改
Trim21 <notifications@github.com>于2017年5月30日 周二下午12:30写道：

**Comment by trim21** [comment]
这种安装之后通过命令行调用的程序不是很熟悉要怎么测试.......

**Comment by RicterZ** [comment]
尝试下载个东西就好

要么晚点我回去试试…
Trim21 <notifications@github.com>于2017年5月30日 周二下午12:36写道：

**Comment by trim21** [comment]
还有一个问题,看了一下现在的代码逻辑,似乎是只有添加的某个番剧之后新的更新的才会触发下载,而像我这样刚刚想开始用的除发不了任何番剧的下载...还是专门去改了大于号才能下载最新一集.

**Comment by RicterZ** [comment]
这个啊，你添加的时候  `bgmi add "番" --episode 0`

**Comment by RicterZ** [comment]
解决你说的那个的问题有两个方法，一个是 `bgmi add` 后 `bgmi mark` 为 0，另外一种是 `bgmi add` 的时候加上 `--episode=0` 参数，默认为最新的一集。
