### ISSUE TITLE
似乎没考虑到历史剧集的下载？

### ISSUE THREAD

**Issue by dev-techmoe** [RicterZ/BGmi#6]
使用`bgmi update --download`似乎并不能下载历史剧集

**Comment by dev-techmoe** [comment]
好吧知道怎么用了。。  
要用`bgmi mark`更新flag。。

**Comment by RicterZ** [comment]
其实不是 flag 是当前更新到的集数_(:3」∠)_

techmoe notifications@github.com于2016年9月15日 周四下午11:38写道：
