### ISSUE TITLE
bgmi.cfg中 bangumi_moe_url 一项,url结束处的`/`会导致fetch出错

### ISSUE THREAD

**Issue by trim21** [RicterZ/BGmi#60]
写成` bangumi_moe_url = https://bangumi.moe/`就会报错,
` bangumi_moe_url = https://bangumi.moe`就能正常fetch
应该也不算一个bug,但是感觉解析的时候自动去掉结尾的`/`比较好....

**Comment by RicterZ** [comment]
OK
Trim21 <notifications@github.com>于2017年6月6日 周二上午7:02写道：

**Comment by RicterZ** [comment]
fixed
