### ISSUE TITLE
Bangumi 合集发布处理

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/BGmi#63]

**Comment by RicterZ** [comment]
[UHA-WINGS][为美好的世界献上祝福！2][Kono Subarashii Sekai ni Shukufuku o! 3][s2- 01-10 END 合集][720p][GB]
    [UHA-WINGS][为美好的世界献上祝福！2][Kono Subarashii Sekai ni Shukufuku o! 2][s2- 01-10 END 合集][720p][BIG5]

标记为合集并分别处理大概很蛋疼。

**Comment by RicterZ** [comment]
考虑要不要有合集关键字就 ignore 了算了..

**Comment by trim21** [comment]
添加一个补番功能fetch合集,原来的订阅就把合集ignore掉

**Comment by RicterZ** [comment]
可以

**Comment by RicterZ** [comment]
补番这个其实可以自行通过 #64 来..
