### ISSUE TITLE
搜索并下载旧番

### ISSUE THREAD

**Issue by RicterZ** [RicterZ/BGmi#64]

**Comment by RicterZ** [comment]
![image](https://user-images.githubusercontent.com/5282759/27254122-643671ee-53b4-11e7-8933-e2ffa59019af.png)
大概这样

**Comment by RicterZ** [comment]
3dc0d2934e3abbcfa9c371c9b339b0e7bba7619a

**Comment by RicterZ** [comment]
cc @wfjsw

就是正则写起来蛋疼但是至少实现了

**Comment by wfjsw** [comment]
可以用tag表来选嘛
比正则好一点（

**Comment by RicterZ** [comment]
tag好麻烦（瘫倒
Jabasukuriputo Wang <notifications@github.com>于2017年6月17日 周六下午11:43写道：

**Comment by wfjsw** [comment]
也可以本地缓存一下tag名到id的映射嘛（
我记着用tag要简单和准确很多啊x
