### ISSUE TITLE
windows python3环境下终端输出乱码

### ISSUE THREAD

**Issue by trim21** [RicterZ/BGmi#68]
环境:
- windows
- cmder
- python3

为什么`main.py`里面要有这两行代码..........

>if bgmi.config.IS_PYTHON3:
>    unicode = str
>    ***file_ = sys.stdout.buffer***
>    ***sys.stdout = codecs.getwriter(locale.getpreferredencoding())(file_)***

在使用了`export PYTHONIOENCODING=utf8`之后`print()`仍然会强制输出gbk编码的,覆盖了环境变量中的设置,在终端设置了uft-8编码后不仅会乱码,而且因为某些unicode无法转化为gbk还会报错.
`UnicodeEncodeError: 'gbk' codec can't encode character '\u266d' in position 9: illegal multibyte sequence`

似乎这里是想设置合适的输出编码?
但是正确的方法应该是在环境变量中设置`PYTHONIOENCODING`吧....python2的实现中使用了`sys.setdefaultencoding('utf-8')`,搜索了一下也是不推荐的方法,
[Dangers of sys.setdefaultencoding('utf-8')](https://stackoverflow.com/questions/28657010/dangers-of-sys-setdefaultencodingutf-8)

**Comment by RicterZ** [comment]
求 PR（偷个懒，没环境..
因为要保证 Linux / macOS / Windows 下 python2 / python3 的输出都没问题，很蛋疼（。

**Comment by trim21** [comment]
我也没有MacOS的环境（
所以这两行代码在MacOS下是正确的吗

**Comment by trim21** [comment]
大概是因为Linux和MacOS的终端默认编码就是utf8所以不会出现覆盖的问题。。。

**Comment by RicterZ** [comment]
这个 tput cols 对于每个 windows 版本都 work 嘛？

**Comment by trim21** [comment]
如果是cmd和powershell的话在上面就已经取得结果return了，只有git bash在if条件下取不到结果，函数会没有返回值。后面nonetype跟int做大小比较会报错。而git bash是自带tput的 所以只会影响Windows下的git bash用户。

**Comment by trim21** [comment]
影响：原来会报nonetype无法跟int做<运算 现在修复了

**Comment by trim21** [comment]
至于每个Windows版本。。。我没有win7设备，不知道在win7下工作不工作了（
