### ISSUE TITLE
更细致的 bangumi filter

### ISSUE THREAD

**Issue by xdujiang** [RicterZ/BGmi#7]
有时一个字幕组会出简体繁体两组或者是不同清晰度的多种视频，在校园网流量有限的情况下全部下载就比较伤了...
可以考虑加个过滤器排除标题的特定关键字么...

btw，使用bgmi install安装时总是失败，提示

> error: unrecognized arguments: install, try '-h' for help

**Comment by RicterZ** [comment]
bgmi install 的问题我先修一下，但是 filter 有点难…要适配各种情况，需要考虑一下怎么做。

比如简繁体不同的番不一样，有的番没有分辨率的关键词…

xdujiang notifications@github.com于2016年9月17日 周六下午1:55写道：

**Comment by RicterZ** [comment]
你说的那个问题按理说只会下载一个来着
Ricter Zheng ricterzheng@gmail.com于2016年9月17日 周六下午6:47写道：

**Comment by xdujiang** [comment]
这个月流量有点不足，所以我还没测试具体的下载情况...我是根据截图推测可能会出现多版本的问题的...
filter的话，感觉可以考虑用“include”、“exclude”根据标题来选择、排除资源，以"線上遊戲的老婆不可能是女生？"来举例，可以考虑用
`bgmi filter "線上遊戲的老婆不可能是女生？" "KNA,惡魔島" /include "720P" /exclude “BIG5”`
之类的组合来选取指定字幕组资源中标题包含“720P”，不包含“BIG5”的资源简体中文720P资源。
当然这只是我的想法...不知道好不好实现...

**Comment by RicterZ** [comment]
可以的，应该可以实现

**Comment by xdujiang** [comment]
了解，感谢回复~

**Comment by RicterZ** [comment]
f4487f2c23379b3b60ef30d3ae2e836a028fe2ae
bb99226f2259564bae331c1177be041de6c2ec4c

**Comment by RicterZ** [comment]
现在可以辣！

**Comment by RicterZ** [comment]
43d3ea6

**Comment by xdujiang** [comment]
的确好了~辛苦了~
不过bgmi install还是不行啊...

**Comment by RicterZ** [comment]
install 有什么错，求新开一个 issue😂
xdujiang notifications@github.com于2016年10月21日 周五下午9:33写道：
