### ISSUE TITLE
和教程写的不一样啊

### ISSUE THREAD

**Issue by QYQSDTC** [RicterZ/BGmi#75]
![image](https://user-images.githubusercontent.com/15608306/28266245-6723fc3a-6b26-11e7-9395-9c4644990df0.png)
是不是我哪里没弄对。。。

**Comment by RicterZ** [comment]
没有，数据挂了？

http://bangumi_moe.ricterz.me/api/bangumi/current
http://bangumi_moe.ricterz.me/api/team/working
http://bangumi_moe.ricterz.me/api/tag/fetch

这三个链接返回了不是 json 的数据

**Comment by RicterZ** [comment]
你curl看一看

**Comment by trim21** [comment]
bgmi cal可以正常显示...

**Comment by RicterZ** [comment]
可能是哪里挂了然后502…我这里也很迷…
Trim21 <notifications@github.com>于2017年7月18日 周二上午12:52写道：

**Comment by trim21** [comment]
all选项被你注释掉了- -
```python
    # sub_parser_cal.add_argument('filter', type=unicode_, metavar='filter', choices=FILTER_CHOICES,
    #                             help='Calendar form filter ({}).'.format(', '.join(FILTER_CHOICES)))
```

**Comment by trim21** [comment]
文件上面的这几行被去掉了
```python
FILTER_CHOICE_TODAY = 'today'
FILTER_CHOICE_ALL = 'all'
FILTER_CHOICE_FOLLOWED = 'followed'
FILTER_CHOICES = (FILTER_CHOICE_ALL, FILTER_CHOICE_FOLLOWED, FILTER_CHOICE_TODA
```

**Comment by RicterZ** [comment]
all 是我去掉的，新版本直接 cal 就行，没必要再加一个 all，麻烦
Trim21 <notifications@github.com>于2017年7月18日 周二上午1:07写道：

**Comment by trim21** [comment]
然而readme忘了改了(

**Comment by RicterZ** [comment]
……尴尬
Trim21 <notifications@github.com>于2017年7月18日 周二上午1:12写道：

**Comment by QYQSDTC** [comment]
我的还是说返回的数据不是jason啊。。。。

**Comment by RicterZ** [comment]
你看我第一条回复，那三个地址挨个 curl 一下给我看看
YiQian Qian <notifications@github.com>于2017年7月18日 周二上午10:25写道：

**Comment by QYQSDTC** [comment]
![image](https://user-images.githubusercontent.com/15608306/28298679-41c39ece-6ba7-11e7-9eae-a78f1bc5cf36.png)
@RicterZ

**Comment by RicterZ** [comment]
没问题的呀…

你 export DEBUG=1 然后 bgmi cal 看看。
实在不行就 bgmi config 把 BANGUMI_MOE_URL 改为 https://bangumi.moe

**Comment by trim21** [comment]
配置里是不是改成bangumi.moe又忘记改成https了……

**Comment by QYQSDTC** [comment]
![image](https://user-images.githubusercontent.com/15608306/28299167-318edae8-6baa-11e7-8095-0e2e3ffcd7fe.png)
改了config好了

**Comment by RicterZ** [comment]
emm是我 nginx 反向代理的问题…
具体原因我也查不清…换了台服务器就这样了，之前我也遇到过😂😂😂
YiQian Qian <notifications@github.com>于2017年7月18日 周二上午11:14写道：

**Comment by trim21** [comment]
这样反代一下的意义是什么……

**Comment by RicterZ** [comment]
你们那里bangumi.moe打开速度快吗？我这里超级慢…
Trim21 <notifications@github.com>于2017年7月18日 周二下午2:12写道：

**Comment by QYQSDTC** [comment]
我的还行，又出了一个问题，Aria2 怎么下BT，搞了半天不行😂

**Comment by trim21** [comment]
全部加载完要10s...有几个静态文件实在是太慢了
@QYQSDTC aria2默认设置就可以下bt啊..你的aria2出什么问题了

**Comment by RicterZ** [comment]
README 已更新
