### ISSUE TITLE
更换新番封面源？

### ISSUE THREAD

**Issue by yukiinagato** [RicterZ/BGmi#9]
> GET http://bangumi.redrock-team.com/static/assets/c7279cce1bf905cdc1527b439c38d370.jpg 403 (Forbidden)
> (index):425 GET http://bangumi.redrock-team.com/static/assets/8df4356a2b3f7eddbf693495b322cc4a.jpg 403 (Forbidden)
> (index):425 GET http://bangumi.redrock-team.com/static/assets/f93360b5787b0f0db6dd5464b95a0bd4.jpg 403 (Forbidden)
> (index):425 GET http://bangumi.redrock-team.com/static/assets/12420b42a39386f803621ca9ef1dbdca.jpg 403 (Forbidden)
> (index):425 GET http://bangumi.redrock-team.com/static/assets/53c9415d02787c41b0f053671a47e1be.jpg 403 (Forbidden)
> (index):425 GET http://bangumi.redrock-team.com/static/assets/e8a71f38de9965427c471e2fcbedcb15.jpg net::ERR_CONNECTION_RESET

有代替的源吗？

**Comment by RicterZ** [comment]
啊我学弟把外网访问给ban了…我想想放哪😂
Takashi Mine notifications@github.com于2016年9月25日 周日下午5:46写道：

**Comment by yukiinagato** [comment]
渣浪，或者整合进仓库里？我搭一个也可以

All the best,
OX

---

Phone: +81-6-4560-2922
Website: https://www.ooxx.dk https://www.ooxx.dk/
E-mail:  github@ooxx.dk mailto:github@ooxx.dk

**Comment by RicterZ** [comment]
最新版本已经可以修改封面地址了，默认在 http://bangumi.ricterz.me/images/
就是慢了点，不过可以自己搭建，过往封面地址：http://bangumi.ricterz.me/images/cover.tar.gz

**Comment by RicterZ** [comment]
可以通过 `bgmi config COVER_URL "http://your.cover.com/images/"` 设置

**Comment by yukiinagato** [comment]
> e8a71f38de9965427c471e2fcbedcb15.jpg
> f93360b5787b0f0db6dd5464b95a0bd4.jpg
> 53c9415d02787c41b0f053671a47e1be.jpg

404

**Comment by RicterZ** [comment]
这是哪几部番，其实都是我手动添加的，名字是md5(番的名字).jpg，如果没有的话得自己手动爬（逃

Takashi Mine notifications@github.com于2016年9月26日 周一上午12:24写道：
